services:
    Mroi\ContaoAddons\Utilities\CSVDownloader:
        tags:
            - { name: contao.hook, hook: loadDataContainer }
            - { name: contao.hook, hook: loadLanguageFile }
    Mroi\ContaoAddons\Utilities\LogMailer:
        arguments:
            - '@contao.repository.cron_job'
        tags:
            - { name: contao.cronjob, interval: daily }
